"""modelo inicial bancocloud

Revision ID: 2444bc94d194
Revises: 
Create Date: 2026-09-17 20:56:41.399037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2444bc94d194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=50), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_entidad', 'audit_log', ['entidad', 'entidad_id'], unique=False)
    op.create_index(op.f('ix_audit_log_fecha_hora'), 'audit_log', ['fecha_hora'], unique=False)
    op.create_table('cliente',
    sa.Column('cliente_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('segmento', sa.String(length=20), nullable=False),
    sa.Column('fecha_alta', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('activo','bloqueado','cerrado')", name='ck_cliente_estado'),
    sa.CheckConstraint("segmento IN ('joven','clasico','premium','empresa')", name='ck_cliente_segmento'),
    sa.CheckConstraint("tipo_documento IN ('DNI','CE','PASAPORTE')", name='ck_cliente_tipo_documento'),
    sa.PrimaryKeyConstraint('cliente_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('genai_log',
    sa.Column('genai_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caso_uso', sa.String(length=30), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('prompt_enmascarado', sa.Text(), nullable=False),
    sa.Column('respuesta_cruda', sa.Text(), nullable=False),
    sa.Column('decision_humana', sa.String(length=200), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('genai_log_id')
    )
    op.create_table('cuenta',
    sa.Column('cuenta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=20), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha_apertura', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('activa','bloqueada','cerrada')", name='ck_cuenta_estado'),
    sa.CheckConstraint("moneda IN ('PEN','USD')", name='ck_cuenta_moneda'),
    sa.CheckConstraint("tipo_cuenta IN ('ahorro','corriente')", name='ck_cuenta_tipo'),
    sa.CheckConstraint('saldo >= 0', name='ck_cuenta_saldo_no_negativo'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('cuenta_id')
    )
    op.create_index(op.f('ix_cuenta_cliente_id'), 'cuenta', ['cliente_id'], unique=False)
    op.create_table('prestamo',
    sa.Column('prestamo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tasa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('fecha_desembolso', sa.Date(), nullable=True),
    sa.Column('dias_mora', sa.Integer(), nullable=False),
    sa.Column('bucket_mora', sa.String(length=5), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("bucket_mora IN ('0','1-30','31-60','61-90','>90')", name='ck_prestamo_bucket'),
    sa.CheckConstraint("estado IN ('solicitado','aprobado','rechazado','vigente','cancelado')", name='ck_prestamo_estado'),
    sa.CheckConstraint('dias_mora >= 0', name='ck_prestamo_dias_mora'),
    sa.CheckConstraint('monto_original > 0', name='ck_prestamo_monto_positivo'),
    sa.CheckConstraint('plazo BETWEEN 1 AND 60', name='ck_prestamo_plazo_meses'),
    sa.CheckConstraint('saldo_capital >= 0', name='ck_prestamo_saldo_no_negativo'),
    sa.CheckConstraint('tasa >= 0 AND tasa <= 100', name='ck_prestamo_tasa'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('prestamo_id')
    )
    op.create_index(op.f('ix_prestamo_cliente_id'), 'prestamo', ['cliente_id'], unique=False)
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.CheckConstraint("rol IN ('cliente','analista','admin')", name='ck_usuario_rol'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('cliente_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('queja',
    sa.Column('queja_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('categoria_sugerida', sa.String(length=20), nullable=True),
    sa.Column('confianza', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('categoria_final', sa.String(length=20), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=False),
    sa.Column('revisado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("categoria_final IS NULL OR categoria_final IN ('tarjeta','prestamo','cuenta','canal_digital','atencion','otro')", name='ck_queja_cat_final'),
    sa.CheckConstraint("categoria_sugerida IS NULL OR categoria_sugerida IN ('tarjeta','prestamo','cuenta','canal_digital','atencion','otro')", name='ck_queja_cat_sugerida'),
    sa.CheckConstraint("estado_revision IN ('pendiente','confirmada','corregida')", name='ck_queja_estado_revision'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.cliente_id'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('queja_id')
    )
    op.create_index(op.f('ix_queja_cliente_id'), 'queja', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_queja_estado_revision'), 'queja', ['estado_revision'], unique=False)
    op.create_table('resumen_ejecutivo',
    sa.Column('resumen_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('kpis_entrada', sa.Text(), nullable=False),
    sa.Column('texto_generado', sa.Text(), nullable=False),
    sa.Column('texto_final', sa.Text(), nullable=True),
    sa.Column('estado_revision', sa.String(length=20), nullable=False),
    sa.Column('revisado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado_revision IN ('pendiente','aprobado','rechazado')", name='ck_resumen_estado_revision'),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('resumen_id')
    )
    op.create_table('tarjeta',
    sa.Column('tarjeta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tarjeta', sa.String(length=10), nullable=False),
    sa.Column('ultimos_4', sa.String(length=4), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('activa','bloqueada','vencida')", name='ck_tarjeta_estado'),
    sa.CheckConstraint("tipo_tarjeta IN ('debito','credito')", name='ck_tarjeta_tipo'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.cuenta_id'], ),
    sa.PrimaryKeyConstraint('tarjeta_id')
    )
    op.create_index(op.f('ix_tarjeta_cuenta_id'), 'tarjeta', ['cuenta_id'], unique=False)
    op.create_table('transaccion',
    sa.Column('transaccion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_origen_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_destino_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.CheckConstraint("canal IN ('web','app','cajero','agente','sistema')", name='ck_transaccion_canal'),
    sa.CheckConstraint("estado IN ('aplicada','rechazada','reversada')", name='ck_transaccion_estado'),
    sa.CheckConstraint("tipo IN ('deposito','retiro','transferencia','pago_prestamo','comision')", name='ck_transaccion_tipo'),
    sa.CheckConstraint('monto > 0', name='ck_transaccion_monto_positivo'),
    sa.ForeignKeyConstraint(['cuenta_destino_id'], ['cuenta.cuenta_id'], ),
    sa.ForeignKeyConstraint(['cuenta_origen_id'], ['cuenta.cuenta_id'], ),
    sa.PrimaryKeyConstraint('transaccion_id')
    )
    op.create_index(op.f('ix_transaccion_cuenta_destino_id'), 'transaccion', ['cuenta_destino_id'], unique=False)
    op.create_index(op.f('ix_transaccion_cuenta_origen_id'), 'transaccion', ['cuenta_origen_id'], unique=False)
    op.create_index('ix_transaccion_fecha_hora', 'transaccion', ['fecha_hora'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaccion_fecha_hora', table_name='transaccion')
    op.drop_index(op.f('ix_transaccion_cuenta_origen_id'), table_name='transaccion')
    op.drop_index(op.f('ix_transaccion_cuenta_destino_id'), table_name='transaccion')
    op.drop_table('transaccion')
    op.drop_index(op.f('ix_tarjeta_cuenta_id'), table_name='tarjeta')
    op.drop_table('tarjeta')
    op.drop_table('resumen_ejecutivo')
    op.drop_index(op.f('ix_queja_estado_revision'), table_name='queja')
    op.drop_index(op.f('ix_queja_cliente_id'), table_name='queja')
    op.drop_table('queja')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_prestamo_cliente_id'), table_name='prestamo')
    op.drop_table('prestamo')
    op.drop_index(op.f('ix_cuenta_cliente_id'), table_name='cuenta')
    op.drop_table('cuenta')
    op.drop_table('genai_log')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_audit_log_fecha_hora'), table_name='audit_log')
    op.drop_index('ix_audit_entidad', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
