"""libro mayor partida doble

Revision ID: b0328a02a241
Revises: 2444bc94d194
Create Date: 2026-09-20 13:05:26.130100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.contabilidad import filas_seed_plan_de_cuentas


# revision identifiers, used by Alembic.
revision: str = 'b0328a02a241'
down_revision: Union[str, Sequence[str], None] = '2444bc94d194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_CUENTA_CONTABLE = sa.table(
    "cuenta_contable",
    sa.column("codigo", sa.String),
    sa.column("nombre", sa.String),
    sa.column("naturaleza", sa.String),
    sa.column("tipo", sa.String),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuenta_contable',
    sa.Column('cuenta_contable_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('naturaleza', sa.String(length=1), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.CheckConstraint("naturaleza IN ('D','H')", name='ck_cuenta_contable_naturaleza'),
    sa.CheckConstraint("tipo IN ('activo','pasivo','patrimonio','ingreso','gasto')", name='ck_cuenta_contable_tipo'),
    sa.PrimaryKeyConstraint('cuenta_contable_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('asiento_contable',
    sa.Column('asiento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_contable', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('tipo_operacion', sa.String(length=30), nullable=False),
    sa.Column('transaccion_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('asiento_reversa_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("estado IN ('contabilizado','reversado')", name='ck_asiento_estado'),
    sa.ForeignKeyConstraint(['asiento_reversa_id'], ['asiento_contable.asiento_id'], ),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transaccion.transaccion_id'], ),
    sa.PrimaryKeyConstraint('asiento_id')
    )
    op.create_table('movimiento_contable',
    sa.Column('movimiento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_contable_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=1), nullable=False),
    sa.Column('importe', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.CheckConstraint("moneda IN ('PEN','USD')", name='ck_movimiento_moneda'),
    sa.CheckConstraint("tipo_movimiento IN ('D','H')", name='ck_movimiento_tipo'),
    sa.CheckConstraint('importe > 0', name='ck_movimiento_importe_positivo'),
    sa.ForeignKeyConstraint(['asiento_id'], ['asiento_contable.asiento_id'], ),
    sa.ForeignKeyConstraint(['cuenta_cliente_id'], ['cuenta.cuenta_id'], ),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['cuenta_contable.cuenta_contable_id'], ),
    sa.PrimaryKeyConstraint('movimiento_id')
    )
    op.create_index('ix_movimiento_asiento', 'movimiento_contable', ['asiento_id'], unique=False)
    op.create_index('ix_movimiento_cuenta_cliente', 'movimiento_contable', ['cuenta_cliente_id'], unique=False)
    # ### end Alembic commands ###

    # --- objetos que autogenerate no genera: se agregan a mano (ver HU-Libro-Mayor-Partida-Doble.md DoD) ---

    # Plan de cuentas minimo (dato de configuracion del sistema, no de prueba).
    op.bulk_insert(_CUENTA_CONTABLE, filas_seed_plan_de_cuentas())

    # Indice unico FILTRADO: a lo sumo un asiento ORIGINAL por transaccion; una reversion
    # (tipo_operacion = 'reversion') si puede repetir transaccion_id.
    op.execute("""
        CREATE UNIQUE INDEX ux_asiento_transaccion_original
            ON dbo.asiento_contable(transaccion_id)
            WHERE transaccion_id IS NOT NULL AND tipo_operacion <> 'reversion'
    """)

    # Defensa en profundidad (V6): el service ya valida Sigma DEBE = Sigma HABER en codigo;
    # este trigger es el respaldo a nivel de motor si un bug futuro lo pasara por alto.
    op.execute("""
        CREATE TRIGGER trg_asiento_balanceado
        ON dbo.movimiento_contable
        AFTER INSERT
        AS
        BEGIN
            IF EXISTS (
                SELECT asiento_id
                FROM inserted
                GROUP BY asiento_id
                HAVING SUM(CASE WHEN tipo_movimiento = 'D' THEN importe ELSE -importe END) <> 0
            )
                THROW 50001, 'Asiento contable no balanceado: Sigma DEBE debe ser igual a Sigma HABER', 1;
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # objetos agregados a mano en upgrade(): se revierten primero (por claridad; SQL Server ya
    # los elimina en cascada al hacer DROP TABLE, pero un downgrade explicito no depende de eso).
    op.execute("DROP TRIGGER IF EXISTS trg_asiento_balanceado")
    op.execute("DROP INDEX IF EXISTS ux_asiento_transaccion_original ON dbo.asiento_contable")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movimiento_cuenta_cliente', table_name='movimiento_contable')
    op.drop_index('ix_movimiento_asiento', table_name='movimiento_contable')
    op.drop_table('movimiento_contable')
    op.drop_table('asiento_contable')
    op.drop_table('cuenta_contable')
    # ### end Alembic commands ###
